### ISSUE TITLE
lobid-organisations frontend

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#132]
We will start with a search field, then adding different filters for the result list.

**Comment by fsteeg** [comment]
Related issues:

- [ ] Provide HTML views for organisation descriptions: https://github.com/hbz/lobid-organisations/issues/33
- [ ] Translate index page content: https://github.com/hbz/lobid-organisations/issues/63
- [ ] Serve `en` or `de` index pages based on language header: https://github.com/hbz/lobid-organisations/issues/64
- [ ] Define correction workflow for DBS data: https://github.com/hbz/lobid-organisations/issues/94

**Comment by fsteeg** [comment]
This is an aggregation issue, with actual tasks in `ready`. Moving this to `backlog` to unclutter `ready`.

**Comment by fsteeg** [comment]
Frontend is implemented: http://beta.lobid.org/organisations

No more open UI-specific issues, closing.
